### ISSUE TITLE
와이어프레임

### ISSUE THREAD

**Issue by eunbiiKim** [eunbiiKim/ToDoApp-iOS#16]

**Comment by eunbiiKim** [comment]
[ToDoUI.xd.zip](https://github.com/eunbiiKim/ToDoApp-iOS/files/3326283/ToDoUI.xd.zip)

**Comment by jaemyeong** [comment]
https://xd.adobe.com/spec/dc942275-e42f-4070-7a2f-3c2c5afeb850-aaa5/

**Comment by jaemyeong** [comment]
`wireframe.zip` 레이블이 적절하지 않아 제거 하는게 좋을 것 같습니다.

**Comment by jaemyeong** [comment]
와이어프레임도 문서의 일종이니 `documentation` 레이블을 사용하는게 좋을 것 같네요.
