### ISSUE TITLE
.gitignore 파일 추가

### ISSUE THREAD

**Issue by yejun614** [eunbiiKim/ToDoApp-iOS#17]
xcode에서 프로젝트 여닌깐 파일이 추가로 생기네요? 아마 .gitignore 파일이 필요할 거 같습니다.

**Comment by dp221125** [comment]
어떤 파일이 추가로 생기나요?

**Comment by yejun614** [comment]
ToDo.xcodeproj/xcuserdata/jungyejun.xcuserdatad/
이런 파일이 생겨요. 아마도 개인 xcode 파일인거 같아요.

**Comment by JaeungHyun** [comment]
개인설정파일이에요

**Comment by yejun614** [comment]
그냥 .gitignore 없이 커밋할 때 무시하는게 맞을까요?

**Comment by JaeungHyun** [comment]
gitignore에 추가하는게 좋을것 같아요

https://www.gitignore.io

여기 들어가면 자동으로 만들어줍니다

**Comment by yejun614** [comment]
그런데 제가 아직 git에 익숙하지가 않아서 ㅠㅠ
지금 브랜치 잘못 건들인거 같은데... 한번 확인해 주실 수 있나요?

**Comment by JaeungHyun** [comment]
> 그런데 제가 아직 git에 익숙하지가 않아서 ㅠㅠ
> 지금 브랜치 잘못 건들인거 같은데... 한번 확인해 주실 수 있나요?

얼추 맞는것 같네요

**Comment by yejun614** [comment]
실수로 커밋 메세지에 이슈 번호 입력하는걸 잊었는데 커밋 메세지 수정 될까요?

**Comment by JaeungHyun** [comment]
git commit --amend -m "수정커밋" 이렇게 하면 될거에요

**Comment by jaemyeong** [comment]
어차피 master 브랜치는 보호 걸어놔서 푸시 못하니까 마음것 브랜치 작업하세요.

**Comment by jaemyeong** [comment]
지금 저희 프로젝트 기준 gitignore.io 에서 swift,xcode,macos 정도면 됩니다.

**Comment by jaemyeong** [comment]
`.gitignore` 파일만드시고 `git rm --cached -r .` 하시고 `git add .`하시면 추가됬던 개인파일 git 에서 제거 되고 gitignore 패턴에 따라서 다시 추가될거에요.

**Comment by yejun614** [comment]
어떻게든 된거 같네요... 감사합니다!
